# Generated by Django 5.0.4 on 2024-04-06 23:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prename', models.CharField(max_length=50)),
                ('signInDate', models.DateField(default=datetime.datetime.now)),
                ('birth', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('picture', models.FileField(upload_to='pictures')),
            ],
        ),
    ]
